### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by ner-sk** [CHATWA/Road_Disease_Target_Detection#1]
请问作者，这个数据集你自己收集的吗？有相应论文发表吗？

**Comment by CHATWA** [comment]
> 请问作者，这个数据集你自己收集的吗？有相应论文发表吗？

你好，数据集不是本人收集，是一个比赛提供的数据集（第五届全球校园人工智能算法精英大赛—【算法挑战赛】道路病害目标检测），据我了解没有论文发表

**Comment by ner-sk** [comment]
感谢您的回复，我在赛氪上找到了这个比赛但是已经结束了，您能帮我拉到这个比赛的qq群里吗？我的qq是1914366379

**Comment by CHATWA** [comment]
> 感谢您的回复，我在赛氪上找到了这个比赛但是已经结束了，您能帮我拉到这个比赛的qq群里吗？我的qq是1914366379

已添加，请查收
